on:
  workflow_dispatch:
  push:
    paths:
      - workflows/**
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.DHALL_CI_TEST}}
      - uses: dhall-lang/setup-dhall@v4
        with:
          version: '1.28.0'
      - run: dhall version
      - run: dhall-to-yaml --file workflows/main.dhall > .github/workflows/main.yml
      - run: |
          git add .github/workflows/main.yml
          git commit -m "Change in dhall workflow"
          git push
