on:
  workflow_dispatch:
  push:
    paths:
      - workflows/**
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.DHALL_CI_TEST}}
      - uses: dhall-lang/setup-dhall@v4
        with:
          version: '1.28.0'
      - uses: tj-actions/changed-files@v35.7.6
        id: changed-workflow-files
        with:
          files: workflows/**
      - run: dhall version
      - run: |
          for x in ${{steps.changed-workflow-files.outputs.modified_files}}; do
            curfile=(basename "$x" .dhall)
            dhall-to-yaml --file workflows/$curfile.dhall > .github/workflows/$curfile.yml
          done
      - run: |
          git config --global user.email "robot@example.com"
          git config --global user.name "Dhall Bot"
          git add .github/workflows/
          git commit -m "Change in dhall workflow"
          git push
